### PR TITLE
Added Screen Headers through the Screen Widget

### PR DESCRIPTION
**Pull request by susanto-tm**
Screen headers are set in the screen widget and can "turn off" features of the header (ie. only select either text, background image, switch (toggles), or profile -- or combination).

### CODE REVIEW

**Review by rsquared226 — COMMENTED** [review]
For some reason the image isn't showing up for a while on Android, like 10 seconds or so. Other than that it seems like it works

**Review by rsquared226 — COMMENTED** [review]
But other than that it does look super good, should we debug it after break?

**Comment by susanto-tm** [comment]
Yeah it happens to me too. I think it might be too HD. I can try compress it a little more.

**Comment by susanto-tm** [comment]
Images should be loading properly now.

**Review by rsquared226 — APPROVED** [review]
Works awesome now! Feel free to merge when you'd like to

**Pull request merged**
