### PR TITLE
Upgraded Dart and Flutter dependencies to support Null Safety.

### PR DESCRIPTION
**Pull request by susanto-tm**
To test the upgraded version run: `pub get` first. If trying on iOS, run `pub get` then fix any pod issues. Run `pod install` in the `ios` directory then if there are any errors just run whatever the troubleshooting says.

### CODE REVIEW

**Review by rsquared226 — COMMENTED** [review]
I went through the basics of null-safety and skimming through the code it makes sense to me and the app runs!
But when running it I seem to get a bunch of `W/NetworkRequest( 6964): No App Check token for request.` and also something about SvgTheme, maybe it's coming from the sponsorship pics or the huge mountain SVG? I'd need more time to look into it, but here's a snapshot of my console running it:
image

**Comment by rsquared226** [comment]
Yeah now I'm getting a lot of `W/StorageUtil(11200): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: 16:` but like you said everything still works

**Comment by susanto-tm** [comment]
Right now Storage doesn't support App Check so we can't really do anything there. But I setup Firebase App Check for real devices so hopefully that part works fine.

**Comment by rsquared226** [comment]
poggy woggy

**Comment by susanto-tm** [comment]
We should wait to merge other PRs before this one so everyone writes in the upgraded version.

**Review by rsquared226 — APPROVED** [review]

**Pull request merged**
